Removing false information: Dawnguard Epilogues
loot/skyrimse pull request #1532
Opened 2020-12-18 01:14 UTC by SkyLover264

As the mod author of Dawnguard and Clan Volkihar Epilogues (Dawnguard&VolkiharArtifactsQuests.esp), I can tell you with certainty that Legacy of the Dragonborn, and my mod, are not incompatible. I've used them side-by-side since I made it, even with V5 of Legacy, and they work together without a problem.

Likewise, the 4 itms are false reports, and are needed for the mod to work.

2021-01-28 23:00 UTC, pStyl3 commented
The incompatible message was issued in this issue: https://github.com/loot/skyrimse/issues/927
The information comes from this [article](https://www.nexusmods.com/skyrimspecialedition/articles/1494) from the Legacy of the Dragonborn SSE Nexus page.
```
Dawnguard/Clan Volkihar Epilogues - Legacy already has a solution built into it to provide all of the path specific relics from the Dawnguard questlines. Do not install this mod.
```

2021-01-29 05:46 UTC, SkyLover264 commented
I originally responded to the Legacy team's assessment on my own mod page. I'll repost it here:

"Over the past year, I've seen some misinformation spreading that this mod is not compatible with Legacy of the Dragonborn. I would like to shoot that down now. Aside from some duplicate items, this mod and Legacy do NOT interfere with each other in any way, shape, or form. In fact, my mod provides some things that Legacy does not. I've decided to address this here as I am sick and tired of correcting every post I see claiming this. Henceforth, I ask that you not continue to spread this misinformation any further."

2021-01-29 19:20 UTC, themayor897 requested changes
It's irresponsible to completely remove the entry from the masterlist rather than edit it. Also, I think it's wise to wait for the LOTD team to weigh in on this before committing any changes.

2021-01-29 19:27 UTC, themayor897 requested changes

2021-01-29 19:27 UTC, themayor897 commented on masterlist.yaml
> -    inc: [ *LotD_v5 ]
msg: [ *doNotClean ]

2021-01-29 19:27 UTC, themayor897 commented on masterlist.yaml
> -    dirty:
if the donotclean message is added this should be removed.

2021-01-29 19:32 UTC, MacSplody commented
There's a compromise which can be reached regarding the views on compatibility.

I added a message in https://github.com/loot/skyrimse/commit/e464a908dbd10f409b6fb651374dccbff3bcbd35 which could work here. It would need to be added to the `LegacyoftheDragonborn.esm` metadata.

2021-01-29 20:06 UTC, SkyLover264 commented
> It's irresponsible to completely remove the entry from the masterlist rather than edit it. Also, I think it's wise to wait for the LOTD team to weigh in on this before committing any changes.

I don't think their word would be trustworthy here. They hate me.

2021-01-29 20:24 UTC, MacSplody commented on masterlist.yaml
> +
No tabs should be used, only spaces.
```suggestion

```

2021-01-29 20:40 UTC, MacSplody approved these changes

2021-01-29 20:42 UTC, merged

2021-01-29 20:43 UTC, MacSplody commented
@SkyLover264 Thanks.