Add sort instructions for Windhelm Smelterworks
loot/skyrimse pull request #1665
Opened 2021-03-14 14:06 UTC by cecell

2021-03-14 14:34 UTC, sibir-ine requested changes
@cecell Can you add a message for the patch between the two mods?

```yaml
    msg:
      - <<: *patchProvided
        subs: [ 'Windhelm Exterior Altered' ]
        condition: 'active("Windhelm Exterior Altered.esp") and not active("Smelterworks - Windhelm Ext Alt Patch.esp")'
```

Also, can you add the cleaning data?

```yaml
    dirty:
      - <<: *reqManualFix
        crc: 0xAEBCDCBF
        util: '[SSEEdit v4.0.3f](https://www.nexusmods.com/skyrimspecialedition/mods/164)'
        itm: 38
        udr: 1
        nav: 3
      - <<: *reqManualFix
        crc: 0x658B58CA
        util: '[SSEEdit v4.0.3f](https://www.nexusmods.com/skyrimspecialedition/mods/164)'
        nav: 3
```

2021-03-14 14:34 UTC, sibir-ine commented on masterlist.yaml
> +      - 'Windhelm Exterior Altered.esp'
```suggestion
    after: [ 'Windhelm Exterior Altered.esp' ]
```

2021-03-15 02:44 UTC, cecell commented
Sure what you types in is great but I don't know how to make more changes to my commit and I don't see an button to commit your changes.  Your changes look great though

2021-03-15 02:47 UTC, sibir-ine commented
> 
> 
> Sure what you types in is great but I don't know how to make more changes to my commit and I don't see an button to commit your changes.

@cecell You can just make the changes on your local branch & push them; they'll show up here.

2021-03-18 09:55 UTC, sibir-ine approved these changes

2021-03-18 09:57 UTC, merged

2021-03-18 09:57 UTC, sibir-ine commented
@cecell Thanks!