Update to Bears of the North
loot/skyrimse pull request #1750
Opened 2021-04-09 11:48 UTC by ddbb07

- Updated patch messages
- Added patch messages

2021-04-09 13:25 UTC, sibir-ine approved these changes

2021-04-09 13:39 UTC, sibir-ine requested changes

2021-04-09 13:39 UTC, sibir-ine commented on masterlist.yaml
> +        condition: 'active("Monster Mod SE.esm") and not active("Grunt of the North Patch.esp")'
@ddbb07
```suggestion
        condition: 'active("GruntTheBear.esp") and not active("Grunt of the North Patch.esp")'
```

2021-04-10 11:29 UTC, ddbb07 commented on masterlist.yaml
> +        condition: 'active("Monster Mod SE.esm") and not active("Grunt of the North Patch.esp")'
I guess i also missed it

2021-04-10 11:56 UTC, sibir-ine approved these changes

2021-04-10 12:09 UTC, merged