MaddPatch
loot/skyrimse pull request #18
Opened 2017-01-01 07:26 UTC by MaddBomber83

- Several Leveled List type mods did not have their bash tags set.
- - Verified through xEdit

- Added the birds (all of them) and ducks.
- - Ducks want to swim to the top of the list
- - The Birds match up a certain load order

- Two town mods wanted to be after IC

- Bring out the dead wanted to be at the top of the list.

2017-01-01 07:41 UTC, MaddBomber83 commented
Pulled the trigger too soon on that one. My local testing broke somewhere.

2017-01-01 22:36 UTC, Ortham requested changes

2017-01-01 22:36 UTC, WrinklyNinja commented on masterlist.yaml
> +      - 'Skytest'
This is missing a file extension.

2017-01-01 23:57 UTC, MaddBomber83 commented on masterlist.yaml
> +      - 'Skytest'
Fixed!

2017-01-01 23:59 UTC, MaddBomber83 commented
Should I add a -1 Global to mods that directly state they can be loaded anywhere in the list?

2017-01-02 01:06 UTC, Ortham approved these changes

2017-01-02 01:07 UTC, WrinklyNinja commented
> Should I add a -1 Global to mods that directly state they can be loaded anywhere in the list?

No, -1 would mean they should be loaded before any mods which don't have a lower priority.

2017-01-02 01:07 UTC, merged

2017-01-02 04:01 UTC, MaddBomber83 commented
That is the desired effect.

2017-01-02 10:12 UTC, WrinklyNinja commented
"Can load anywhere" is very different from "must load before most plugins".

2017-01-03 04:11 UTC, MaddBomber83 commented
Awesome, ty.  I appreciate all the help you've been giving me.  I've got about half of the documents read; but will likely go back through the first parts again now that I'm dangerously familiar with the process.