Diverse Skyrim - Battle of Whiterun Fix
loot/skyrimse pull request #1808
Opened 2021-05-05 21:10 UTC by PierreDespereaux

Adds a suggestion for the User to download [Diverse Skyrim - Battle of Whiterun Fix](https://www.nexusmods.com/skyrimspecialedition/mods/47939) if they are using Diverse Skyrim.

2021-05-06 01:55 UTC, sibir-ine requested changes

2021-05-06 01:55 UTC, sibir-ine commented on masterlist.yaml
> +        lang: eng
@PierreDespereaux The message can be modified to fit a boilerplate message that already exists, so the end result will be: "It's highly recommended that you also use [Diverse Skyrim - Battle of Whiterun Fix](https://www.nexusmods.com/skyrimspecialedition/mods/47939)."

Also, that language key shouldn't be there.

```suggestion
      - <<: *alsoUseX
        subs: [ '[Diverse Skyrim - Battle of Whiterun Fix](https://www.nexusmods.com/skyrimspecialedition/mods/47939)' ]
```

2021-05-06 01:58 UTC, sibir-ine approved these changes

2021-05-06 02:03 UTC, merged

2021-05-06 02:03 UTC, sibir-ine commented
@PierreDespereaux Thanks!

2021-05-06 02:04 UTC, PierreDespereaux commented
No, thank you :)

2021-05-06 15:33 UTC, MacSplody commented
A similar fix may be included in Immersive Citizens.
![image](https://user-images.githubusercontent.com/1944639/117325389-9562d680-ae88-11eb-99de-05d585b2e9b1.png)

2021-05-08 01:11 UTC, sibir-ine commented
> A similar fix may be included in Immersive Citizens.

It indeed is. I'll add a message for the fix & update this message appropriately.