Updated cleaning info
loot/skyrimse pull request #1911
Opened 2021-06-30 00:27 UTC by ddbb07

- Updated cleaning info for LotD to v5.5.2
- Updated cleaning info for WACCF to v2.4
- Updated cleaning info for Immersive Encounters to v3.2
- Added cleaning info for Animated Eating Redux for 4.4.0
- Updated cleaning info for Undeath - Classical Lichdom to v2.40
- Added cleaning info for Conditional Expressions for 1.12
- Updated cleaning info for Serana Dialogue Add-On to v2.6.3
- Updated cleaning info for Savage Skyrim to v3.95c
- Updated cleaning info for Dynamic Things Alternative to v0.10.1
- Updated cleaning info for Convenient Carriages to v5.8.0 Main CRC: 1C7037D9
- Updated cleaning info for TPOS-C to v9.2.3

2021-06-30 03:58 UTC, sibir-ine requested changes

2021-06-30 03:58 UTC, sibir-ine commented on masterlist.yaml
> +  - name: 'AnimatedEatingRedux.esp'
Can you please add a URL for this mod?

2021-06-30 03:58 UTC, sibir-ine commented on masterlist.yaml
> +  - name: 'Conditional Expressions.esp'
Can you please add a URL for this mod too?

2021-06-30 03:58 UTC, sibir-ine commented on masterlist.yaml
> +      - crc: 0x7C1ABB8D
```suggestion
      - crc: 0x1D19D916
```

This is the checksum of v2.4 of `Weapons Armor Clothing & Clutter Fixes.esp`, not `WACCF_BashedPatchLvlListFix.esp`.

2021-06-30 03:58 UTC, sibir-ine commented on masterlist.yaml
> +      - crc: 0x1C7037D9
This is the checksum of `Convenient Carriages.esp` with the **"Beyond Skyrim - Bruma SE" and "Helgen Reborn"** & **Travel speed tweak - Requires SKSE** options selected in the FOMOD installer. The previous checksum was with the **No optional mods installed** & **Travel speed tweak - Requires SKSE** options selected. It seems excessive to include cleaning data for every possible combination, so I think it'd be best to just report it for the default version & maybe the default + SKSE combo.

2021-06-30 14:48 UTC, ddbb07 commented
Just for your information, this was meant as a draft but i forgot to mark it

2021-08-08 12:47 UTC, pStyl3 commented
@ddbb07 Hey, would it be possible for you to change the things @sibir-ine mentioned? That way we could then merge this PR. And if you'd like to add further cleaning data, that could be done via additional PRs.

2021-08-24 17:31 UTC, MacSplody commented on masterlist.yaml
> +  - name: 'AnimatedEatingRedux.esp'
```suggestion
  - name: 'AnimatedEatingRedux.esp'
    url: [ 'https://www.nexusmods.com/skyrimspecialedition/mods/4652/' ]
```

2021-08-24 17:32 UTC, MacSplody commented on masterlist.yaml
> +  - name: 'Conditional Expressions.esp'
```suggestion
  - name: 'Conditional Expressions.esp'
    url: [ 'https://www.nexusmods.com/skyrimspecialedition/mods/45148/' ]
```

2021-08-24 17:34 UTC, MacSplody commented
Closing as I'm updating some of these files.

2021-08-24 17:34 UTC, closed without merging