Add World Eater Beater
loot/skyrimse pull request #2263
Opened 2021-12-26 22:03 UTC by themayor897

2021-12-26 23:32 UTC, Sabre142 commented
Could be moved to the 'Encounters - Enemies' section.

2021-12-27 08:15 UTC, sibir-ine requested changes
@themayor897 Just requires a few changes. You can also move it to the `Encounters - Enemies` section as Sabre said if you wouldn't mind, but that can always be done later.

2021-12-27 08:15 UTC, sibir-ine commented on masterlist.yaml
> +    url: [ 'https://www.nexusmods.com/skyrimspecialedition/mods/60778' ]
As Sabre said, please add a trailing slash for consistency with the rest of the masterlist.

```suggestion
    url: [ 'https://www.nexusmods.com/skyrimspecialedition/mods/60778/' ]
```

2021-12-27 08:15 UTC, sibir-ine commented on masterlist.yaml
> +    after: [ 'DeadlyDragons.esp' ]
LOOT should sort this way by default, but there's no harm in adding a hard rule just in case.

2021-12-27 08:15 UTC, sibir-ine commented on masterlist.yaml
> +        util: 'SSEEdit v4.0.4'
There should be a newline at the end of the masterlist.

```suggestion
        util: 'SSEEdit v4.0.4'

```

2021-12-29 18:07 UTC, themayor897 commented
Does that look good? Having trouble telling if there's still a new line at the end of the file or not.

2021-12-30 10:44 UTC, sibir-ine approved these changes

2021-12-30 10:53 UTC, merged

2021-12-30 10:53 UTC, sibir-ine commented
@themayor897 Thanks!