Add cleaning ref https://github.com/loot/skyrimse/issues/2287
loot/skyrimse pull request #2306
Opened 2022-01-27 11:53 UTC by cecell

ref https://github.com/loot/skyrimse/issues/2287

2022-01-29 01:58 UTC, sibir-ine requested changes
@cecell, in addition to the suggestions I've made, b632c5d359b0c0f2d6c4b5911391992bada30b0e should also be dropped from this PR & submitted in a separate PR. [Here](https://www.freshconsulting.com/insights/blog/atomic-commits/)'s a good article explaining why you'd want to focus your PRs (they'll be squashed into a single commit, so the reasoning still applies) around a common theme (e.g., adding/updating a mod, updating cleaning data for multiple mods).

2022-01-29 01:58 UTC, sibir-ine commented on masterlist.yaml
> +
There are some trailing whitespaces throughout the PR:

```suggestion

```

2022-01-29 01:58 UTC, sibir-ine commented on masterlist.yaml
> +
```suggestion

```

2022-01-29 01:58 UTC, sibir-ine commented on masterlist.yaml
> +
```suggestion

```

2022-01-29 01:58 UTC, sibir-ine commented on masterlist.yaml
> +        subs: [ 'https://www.nexusmods.com/skyrimspecialedition/articles/2761/' ]
This should be in a separate PR as it's unrelated to the common theme & not a plugin otherwise edited in a way consistent with that theme:

```suggestion
        subs: [ 'https://www.nexusmods.com/skyrimspecialedition/articles/2761']
```

2022-01-29 01:58 UTC, sibir-ine commented on masterlist.yaml
> +        nav: 2
It looks like the latest version of this mod, v2.1, has different cleaning data:

```suggestion
      - <<: *quickClean
        crc: 0xF79DBD87
        util: '[SSEEdit v4.0.4b](https://www.nexusmods.com/skyrimspecialedition/mods/164)'
        udr: 4
```

2022-01-30 20:40 UTC, cecell commented
wow I guess I didn't realize I could have two different PRs at the same time.  I'll have to look at how to do that, sorry

2022-01-30 20:50 UTC, cecell commented
I did pull the updates made in the meantime before reverting.  I guess you can already see that hell if I know

2022-01-30 20:51 UTC, cecell commented on masterlist.yaml
> +        condition: 'active("The Great Cities - Minor Cities and Towns.esp") and not active("RodryksDragonBridge - GCS Dragon Bridge Patch.esp") and not active("The Great Cities of Jk''s North - Rodry
Reverted in 
105e649

2022-01-30 20:51 UTC, cecell commented on masterlist.yaml
> +        condition: 'active("Dawnstar.esp") and not active("JKs Skyrim_(Dawnstar)?(Arth( CRF)? DA DB FA IV RO)?(Arthmoor All)?_Patch?.*\.esp") and not active("The Great Cities of JK''s North - Arthmoo
reverted in 105e649

2022-01-30 20:51 UTC, cecell commented on masterlist.yaml
> +        condition: 'active("Dragon Bridge.esp") and not active("JKs Skyrim_(Dragon Bridge)?(Arth( CRF)? DA DB FA IV RO)?(Arthmoor All)?_Patch?.*\.esp") and not active("The Great Cities of JK''s North
reverted in 105e649

2022-01-30 20:51 UTC, cecell commented on masterlist.yaml
> +        condition: 'active("Rorikstead.esp") and not active("JKs Skyrim_(Rorikstead)?(Arth( CRF)? DA DB FA IV RO)?(Arthmoor All)?_Patch?.*\.esp") and not active("The Great Cities of JK''s North - Art
reverted in 105e649

2022-01-31 08:56 UTC, sibir-ine approved these changes

2022-01-31 08:57 UTC, merged

2022-01-31 09:10 UTC, sibir-ine commented
@cecell Thanks! For future reference, you can revert commits with [`git revert`](https://git-scm.com/docs/git-revert) or by dropping them in an [interactive rebase](https://git-scm.com/docs/git-rebase#_interactive_mode). The latter would be more appropriate (& cleaner) here, but either would be fine as it'll get squashed anyway. You may also want to look into [`git cherry-pick`](https://git-scm.com/docs/git-cherry-pick) so that you can reuse be0457faad74277602113cfb571a96d3b5e8ef09 without having to reimplement your changes there.

2022-01-31 12:11 UTC, cecell commented
Wow will I'm surprised that I managed to do enough correctly for this to be able to be merged.  I haven't done anything via command line yet. I'll have to look into that