Add no patch Caranthir Tower
loot/skyrimse pull request #2313
Opened 2022-02-06 06:35 UTC by cecell

Badersee SE: https://www.nexusmods.com/skyrimspecialedition/mods/16419 and Caranthir Tower https://www.nexusmods.com/skyrimspecialedition/mods/4269 both make landscape/navmesh changes substantial enough to need patching but as it says, none exist at this time

2022-02-06 08:19 UTC, sibir-ine requested changes

2022-02-06 08:19 UTC, sibir-ine commented on masterlist.yaml
> +      - *patch3rdParty_SRPC
There's an extra whitespace here:

```suggestion
      - *patch3rdParty_SRPC
```

2022-02-06 08:55 UTC, MacSplody commented
Someone left this comment on the Caranthir Tower Reborn mod page.
We could add a message for that as well, Bloodchill Manor `cceejsse005-cave.esm`.
I can test it out in a bit if you don't have that file.

![image](https://user-images.githubusercontent.com/1944639/152673890-7c474a1b-6178-4848-b396-7bc182109ade.png)

2022-02-06 14:24 UTC, cecell commented
Hey very cool. Yes please go ahead. I don't have that file

2022-02-06 15:26 UTC, MacSplody commented
> Hey very cool. Yes please go ahead. I don't have that file

Cell Location conflict, not sure how that would be patched.
![image](https://user-images.githubusercontent.com/1944639/152687714-8af0b11a-e6b9-4f0f-9060-f2287db6b2a9.png)

---

Bloodchill Manor location
![image](https://user-images.githubusercontent.com/1944639/152687864-e5e1e168-e63c-4db9-911f-964b14ea2cb8.png)

Referenced by
![image](https://user-images.githubusercontent.com/1944639/152687873-971b6d80-dff1-47c0-ba35-029b6ac0a428.png)

---

Caranthir Tower Reborn location
![image](https://user-images.githubusercontent.com/1944639/152687959-bfb67fd9-4c9d-434d-a9f8-d37f123979ce.png)


Referenced by
![image](https://user-images.githubusercontent.com/1944639/152687971-5540eaeb-2e88-49bf-aca3-f2786fecc876.png)

---

Both add objects to that cell as well.

![image](https://user-images.githubusercontent.com/1944639/152687780-f8fa8690-f84f-4c5d-95ef-9eb3d85dc8bb.png)

![image](https://user-images.githubusercontent.com/1944639/152687817-73d2f89d-15b9-4685-84e4-313fe1470eee.png)

---

So it would also need a `patchUnavailable` message.

2022-02-07 09:27 UTC, sibir-ine approved these changes

2022-02-07 09:29 UTC, merged