Support for Dawn of Skyrim - Modern Patches
loot/skyrimse pull request #2372
Opened 2022-04-10 09:58 UTC by cram42

Tested locally. Being a modular patch, if installed manually it can get confusing what's compatible with what, so this should help.

2022-04-11 06:18 UTC, sibir-ine requested changes, later dismissed
Besides the suggestions I've made, there are a few more stylistic changes you should make for consistency.

First, since you're using a subsection header for your group of plugins, you should use that to sort the group alphabetically within the `3RD Party Patches` section (i.e., just above `DiverseSkyimCivilWarFix.esp`).

Second, for the formatting of message subs, names of mods shouldn't be formatted (i.e., `Example Mod`) while plugin names should just be emboldened (i.e., `**Example.esp**`).

Third, for the messages, they should be sorted alphabetically by their subs.

2022-04-11 06:18 UTC, sibir-ine commented on masterlist.yaml
> +    ### Dawn of Skyrim - Modern Patches ###
There's some extra whitespace, & the subsection header should only be indented once:

```suggestion

  ### Dawn of Skyrim - Modern Patches ###
```

2022-04-11 06:18 UTC, sibir-ine commented on masterlist.yaml
> +    url: [ 'https://www.nexusmods.com/skyrimspecialedition/mods/65467/' ]
You can combine the locations using a regex plugin, & you can also add a name to it so it can be used in the UI:

```suggestion
  - name: 'DoS_MP_Whiterun.*\.esp'
    url:
      - link: 'https://www.nexusmods.com/skyrimspecialedition/mods/65467/'
        name: 'Dawn of Skyrim - Modern Patches'
  - name: 'DoS_MP_Whiterun.esp'
```

2022-04-11 06:18 UTC, sibir-ine commented on masterlist.yaml
> +    url: [ 'https://www.nexusmods.com/skyrimspecialedition/mods/65467/' ]
The rest of the locations can be removed as they're made redundant by the regex plugin:

```suggestion
```

2022-04-11 06:18 UTC, sibir-ine commented on masterlist.yaml
> +    url: [ 'https://www.nexusmods.com/skyrimspecialedition/mods/65467/' ]
```suggestion
```

2022-04-11 06:18 UTC, sibir-ine commented on masterlist.yaml
> +    url: [ 'https://www.nexusmods.com/skyrimspecialedition/mods/65467/' ]
```suggestion
```

2022-04-11 06:18 UTC, sibir-ine commented on masterlist.yaml
> +    url: [ 'https://www.nexusmods.com/skyrimspecialedition/mods/65467/' ]
```suggestion
```

2022-04-11 06:18 UTC, sibir-ine commented on masterlist.yaml
> +    url: [ 'https://www.nexusmods.com/skyrimspecialedition/mods/65467/' ]
```suggestion
```

2022-04-11 06:18 UTC, sibir-ine commented on masterlist.yaml
> +    url: [ 'https://www.nexusmods.com/skyrimspecialedition/mods/65467/' ]
```suggestion
```

2022-04-11 06:18 UTC, sibir-ine commented on masterlist.yaml
> +    url: [ 'https://www.nexusmods.com/skyrimspecialedition/mods/65467/' ]
```suggestion
```

2022-04-11 06:18 UTC, sibir-ine commented on masterlist.yaml
> +    url: [ 'https://www.nexusmods.com/skyrimspecialedition/mods/65467/' ]
```suggestion
```

2022-04-11 06:18 UTC, sibir-ine commented on masterlist.yaml
> +    url: [ 'https://www.nexusmods.com/skyrimspecialedition/mods/65467/' ]
```suggestion
```

2022-04-11 06:18 UTC, sibir-ine commented on masterlist.yaml
> +        condition: 'active("LegacyoftheDragonborn.esm") and not active("DoS_MP_Whiterun_LOTD.esp") and not active("DoS_MP_Whiterun_CWE_LOTD.esp") and not active("DoS_MP_Whiterun_JK_LOTD.esp") and not
Some of the conditions can be simplified with regexes:

```suggestion
        condition: 'active("LegacyoftheDragonborn.esm") and not active("DoS_MP_Whiterun_(JK_)?(CWE_)?LOTD\.esp")'
```

2022-04-11 06:18 UTC, sibir-ine commented on masterlist.yaml
> +        condition: 'active("LegacyoftheDragonborn.esm") and not active("DoS_MP_Whiterun_CWE_LOTD.esp") and not active("DoS_MP_Whiterun_JK_CWE_LOTD.esp")'
```suggestion
        condition: 'active("LegacyoftheDragonborn.esm") and not active("DoS_MP_Whiterun_(JK_)?CWE_LOTD\.esp")'
```

2022-04-11 06:18 UTC, sibir-ine commented on masterlist.yaml
> +        condition: 'active("LegacyoftheDragonborn.esm") and not active("DoS_MP_Whiterun_JK_LOTD.esp") and not active("DoS_MP_Whiterun_JK_CWE_LOTD.esp")'
```suggestion
        condition: 'active("LegacyoftheDragonborn.esm") and not active("DoS_MP_Whiterun_JK_(CWE_)?LOTD\.esp")'
```

2022-04-11 06:18 UTC, sibir-ine commented on masterlist.yaml
> +      - 'DoS_MP_Whiterun_JK_LOTD.esp'
Single-element maps should be written in flow style:

```suggestion
    inc: [ 'DoS_MP_Whiterun_JK_LOTD.esp' ]
```

2022-07-24 17:03 UTC, MacSplody commented
As the suggestions can't be applied for some reason, I'm going to make the changes locally and try to push them to the PR.

2022-07-24 17:19 UTC, MacSplody commented
Okay force push doesn't seem to be working here, so I'll commit this and add the correction separately.

2022-07-24 17:26 UTC, MacSplody commented
> @cram42, besides the suggestions I've made, there are a few more stylistic changes you should make for consistency.
> 
> First, since you're using a subsection header for your group of plugins, you should use that to sort the group alphabetically within the `3RD Party Patches` section (i.e., just above `DiverseSkyimCivilWarFix.esp`).
> 
> Second, for the formatting of message subs, names of mods shouldn't be formatted (i.e., `Example Mod`) while plugin names should just be emboldened (i.e., `**Example.esp**`).
> 
> Third, for the messages, they should be sorted alphabetically by their subs.

Going off their mod page they aren't that active at the moment due to work.
I can add those changes to the PR I'm doing.

2022-07-24 17:28 UTC, merged