Update JK's Skyrim
loot/skyrimse pull request #2380
Opened 2022-04-22 16:01 UTC by loicreynier

This currently fixes the load order between [Rob's Bug Fixes - JK's Skyrim](https://www.nexusmods.com/skyrimspecialedition/mods/63379) and the no lights patch of JK's Skyrim.

Rob's plugin must be loaded before any JK's patch, should I add a `after` for all JK's Skyrim patches in the masterlist?

2022-04-23 05:09 UTC, sibir-ine requested changes

2022-04-23 05:09 UTC, sibir-ine commented on masterlist.yaml
> +      - 'JKs Skyrim - Rob''s Bug Fixes.esp'
Looking at the two in xEdit, they don't actually conflict in any major way. Just the MHDT subrecord of the Tamriel worldspace which probably isn't important to either plugin (also which will most likely get overwritten by something else anyway & I'm not sure even does anything) & a water subrecord in __00009349__ that's probably unintentionally reverted by `JKs_Skyrim_No_Lights_Patch.esp` when it loads after.

That being said, I can see it being the case that either plugin may be updated in a way where load order would matter. In that case, you can use the following regex plugin to cover what appears to be most patches. Feel free to add rules for any others that were missed as you see fit. I've also added a location name & converted the single-element file map to flow style. You'll have to manually place it above all of the other patches but just below `JKs Skyrim.esp`:

```yaml
  - name: 'JKs[ _]Skyrim_.*_Patch\.esp'
    url:
      - link: 'https://www.nexusmods.com/skyrimspecialedition/mods/6289/'
        name: 'JK''s Skyrim'
    after: [ 'JKs Skyrim - Rob''s Bug Fixes.esp' ]
```

2022-05-26 20:39 UTC, loicreynier commented
Sorry it took this long. I removed the No Light patch plugin entry and added your regex plugin entry add the top of JK's Skyrim patches section.

2022-05-27 04:28 UTC, sibir-ine commented on masterlist.yaml
> +    after: [ 'JKs Skyrim - Rob''s Bug Fixes.esp' ]
This should be grouped with JK's Skyrim since they're from the same page. Also, the new subsection header isn't necessary.

2022-05-29 10:56 UTC, loicreynier commented
Is this what you expected?

2022-05-29 20:45 UTC, sibir-ine commented on masterlist.yaml
Yes, you just need to remove the newline separating them:

```suggestion
```

2022-05-29 22:13 UTC, sibir-ine approved these changes
Thanks!

2022-05-29 22:14 UTC, merged