Add More Thalmor Dossiers
loot/skyrimse pull request #2381
Opened 2022-04-22 17:06 UTC by loicreynier

Add [More Thalmor Dossiers](https://www.nexusmods.com/skyrimspecialedition/mods/65059) entry and messages if provided patches are not installed.

2022-04-23 04:11 UTC, sibir-ine requested changes

2022-04-23 04:11 UTC, sibir-ine commented on masterlist.yaml
> +    url: [ 'https://www.nexusmods.com/skyrimspecialedition/mods/65059' ]
URLs should have trailing slashes for consistency & convenience if possible. It's also good to add location names now that they're utilized within the UI:

```suggestion
    url:
      - link: 'https://www.nexusmods.com/skyrimspecialedition/mods/65059/'
        name: 'More Thalmor Dossiers'
```

2022-04-23 04:11 UTC, sibir-ine commented on masterlist.yaml
> +        condition: 'active("LegacyoftheDragonborn.esm") and not active("More Thalmor Dossiers - LotD.esp")'
The `clean` key should come after the `msg` key for consistency:

```suggestion
    msg:
      - <<: *patchProvided
        subs: [ 'Helgen Reborn' ]
        condition: 'active("Helgen Reborn.esp") and not active("More Thalmor Dossiers - Helgen Reborn.esp")'
      - <<: *patchProvided
        subs: [ 'Legacy of the Dragonborn' ]
        condition: 'active("LegacyoftheDragonborn.esm") and not active("More Thalmor Dossiers - LotD.esp")'
    clean:
      - crc: 0xA057DD73
        util: 'SSEEdit v4.0.4'
```

2022-04-24 20:05 UTC, loicreynier commented
Thanks for the revisions, I'll keep that in mind.

2022-04-25 23:36 UTC, sibir-ine approved these changes
Thanks!

2022-04-25 23:40 UTC, merged