Update Schlitzohr's Oakwood
loot/skyrimse pull request #2553
Opened 2022-09-10 14:02 UTC by loicreynier

2022-09-10 14:18 UTC, sibir-ine requested changes
@loicreynier, the mod still has some wild edits, namely the records **00009B96**, **00009B97**, & **00009BB9**. If you want, you can remove the cleaning data instead & update the `wildEdits` message, or we can do it in a separate PR.

2022-09-10 14:28 UTC, loicreynier commented
I removed the cleaning data and added this as `wildEdits`, is it what you expected?

2022-09-10 14:40 UTC, sibir-ine requested changes
Yes, the message just needs to be edited since one of those records is no longer a wild edit. The old checkums & cleaning data (I can't add a suggestion for this) can be dropped too.

2022-09-10 14:40 UTC, sibir-ine commented on masterlist.yaml
>          subs: [ 'Remove **00009B95**, **00009B96**, **00009B97**, & **00009BB9** from **AnotherOakwood.esp**.' ]
```suggestion
        subs: [ 'Remove **00009B96**, **00009B97**, & **00009BB9** from **AnotherOakwood.esp**.' ]
```

2022-09-10 14:40 UTC, sibir-ine commented on masterlist.yaml
> +        condition: 'checksum("AnotherOakwood.esp", 1B9CB7E5) or checksum("AnotherOakwood.esp", EE69FD67) or checksum("AnotherOakwood.esp", BB723686)'
```suggestion
        condition: 'checksum("AnotherOakwood.esp", 1B9CB7E5)'
```

2022-09-11 05:52 UTC, sibir-ine approved these changes
Thanks!

2022-09-11 05:53 UTC, merged