Account for Community Shaders in dependencies
loot/skyrimse pull request #2859
Opened 2023-09-17 22:19 UTC by BrainBlasted

Certain mods that previously required ENBSeries can now be used with Community Shaders and its addons. However, LOOT will show an error if it does not detect ENBSeries.

This commit makes the masterlist check for the presence of the Community Shaders plugin and the required addons where applicable in addition to ENBSeries.

2023-09-21 07:15 UTC, MacSplody commented on masterlist.yaml
> +    display: '[Community Shaders](https://www.nexusmods.com/skyrimspecialedition/mods/86492)'
```suggestion
    display: '[Community Shaders](https://www.nexusmods.com/skyrimspecialedition/mods/86492/)'
```

2023-09-21 07:16 UTC, MacSplody commented on masterlist.yaml
> +    display: '[ENBSeries SE](http://enbdev.com/download_mod_tesskyrimse.htm) **OR** [Community Shaders](https://www.nexusmods.com/skyrimspecialedition/mods/86492)'
```suggestion
    display: '[ENBSeries SE](http://enbdev.com/download_mod_tesskyrimse.htm) **OR** [Community Shaders](https://www.nexusmods.com/skyrimspecialedition/mods/86492/)'
```

2023-09-21 07:16 UTC, MacSplody commented on masterlist.yaml
> +        display: '[Complex Parallax Materials](https://www.nexusmods.com/skyrimspecialedition/mods/95134)'
```suggestion
        display: '[Complex Parallax Materials](https://www.nexusmods.com/skyrimspecialedition/mods/95134/)'
```

2023-09-21 07:16 UTC, MacSplody commented on masterlist.yaml
> +        display: '[Light Limit Fix](https://www.nexusmods.com/skyrimspecialedition/mods/99548)'
```suggestion
        display: '[Light Limit Fix](https://www.nexusmods.com/skyrimspecialedition/mods/99548/)'
```

2023-09-21 08:10 UTC, MacSplody requested changes
A few minor changes.

2023-10-28 14:50 UTC, BrainBlasted commented
Applied all requested changes :)

2023-10-29 23:00 UTC, MacSplody approved these changes

2023-10-29 23:07 UTC, merged

2023-10-29 23:07 UTC, MacSplody commented
Thanks.