Merge Updates - ETAC, Lighting Mods, ASLAL: NB & Verdant OCS
loot/skyrimse pull request #288
Opened 2018-08-12 22:48 UTC by CptMcSplody

[New] Expanded Towns and Cities (#282)
Add more incompatible messages for lighting mods (#280)
[NEW] Alternate Start -- New Beginnings (#285)
Flag latest Verdant OCS version as being Incompatible with Open Cities. (#287)

2018-08-12 23:21 UTC, Freso requested changes
Most of the changes here I don't really have an idea about, since I don't know the plugins involved at all, but the logic itself generally seems sane.

Only think I'd want to see here is a small wording (or rather grammar) change, and maybe having the involved `msg` moved up to the `commons` section.

2018-08-12 23:21 UTC, Freso commented on masterlist.yaml
> +        content: 'Plug-ins Masters require sorting.'
I'd say "Plugin’s". We generally use "plugin" without the dash elsewhere in the documentation, and the apostrophe is needed to denote genitive… otherwise we're talking about multiple plugins and then the sentence kind of doesn't make sense anymore. :)

2018-08-12 23:21 UTC, Freso commented on masterlist.yaml
> +        content: 'Plug-ins Masters require sorting.'
If this is repeated, it seems like it should be made an anchor in `commons`.

2018-08-13 00:05 UTC, CptMcSplody commented on masterlist.yaml
> +        content: 'Plug-ins Masters require sorting.'
Okay I cleaned up the grammar, not my strong suit and added the message to `commons`

2018-08-13 00:07 UTC, CptMcSplody commented
Okay I cleaned up the grammar, not my strong suit and added the message to `commons`

2018-08-13 00:09 UTC, CptMcSplody commented on masterlist.yaml
> +        content: 'Plug-ins Masters require sorting.'
Done.

2018-08-13 07:48 UTC, Freso approved these changes
Looks good to me now, but again, I can't comment much on how it'll affect the game, since I haven't done Skyrim since before SSE was a thing. Syntactically it looks fine though. 👍

2018-08-13 07:54 UTC, merged