BandolierForNPC.esp added
loot/skyrimse pull request #289
Opened 2018-08-15 16:42 UTC by coco9515

I added my mod : [BandolierForNPC.esp](https://www.nexusmods.com/skyrimspecialedition/mods/19093) - and 4 others .esp to the list.

All of them required Dr_Bandolier.esp.
BandolierForNPC.esp is the main .esp but :
 - 3 of them are standalone compatibility patch, all the required .esp has been placed.
 - The last one is an optional add-on to my mod or Dr_Bandolier.esp.

2018-08-15 16:47 UTC, WrinklyNinja commented
If you've got a plugin in `req`, you don't need it in `after` too. If you remove the redundant entries, everything else looks fine.

2018-08-15 19:16 UTC, coco9515 commented
Okay, I updated. Is everything okay now ?

2018-08-15 20:19 UTC, MacSplody requested changes
>If manually installing - choose only one

if only one of the below plugins can be installed then an `inc:` key should be used to ensure this.
`BandolierForNPC.esp`
`BandolierForNPC - Cloaks of Skyrim Patch`
`BandolierForNPC - Winter is Coming Patch`
`BandolierForNPC - Winter is Coming and Cloaks of Skyrim Patch`

so for example:

```yaml

  - name: 'BandolierForNPC.esp'
    url:
      - link: 'https://www.nexusmods.com/skyrimspecialedition/mods/19093/'
        name: 'Bandolier - Bags and Pouches for NPC on Nexus Mods'
    inc:
      - 'BandolierForNPC - Cloaks of Skyrim Patch.esp'
      - 'BandolierForNPC - Winter is Coming Patch.esp'
      - 'BandolierForNPC - Winter is Coming and Cloaks of Skyrim Patch.esp'
    tag:
      - Names
      - Stats
```

2018-08-15 20:19 UTC, CptMcSplody commented on masterlist.yaml
> +      - 'Cloaks.esp'
File masters automatically have a required entry, there is no need to add these as required if they're in the `esp` header.

2018-08-15 20:19 UTC, CptMcSplody commented on masterlist.yaml
> +      - '1nivWICCloaks.esp'
Same as above.

2018-08-15 20:19 UTC, CptMcSplody commented on masterlist.yaml
> +      - 'Cloaks.esp'
Same as above.

2018-08-15 20:19 UTC, CptMcSplody commented on masterlist.yaml
> +      - 'Dr_Bandolier.esp'
Also not needed.

2018-08-15 20:19 UTC, CptMcSplody commented on masterlist.yaml
> +      - 'Dr_Bandolier.esp'
Also not needed.

2018-08-15 20:35 UTC, CptMcSplody commented
Also I usually mark mods that have masters in the wrong order as requiring sorting.
`BandolierForNPC - Realistic Enchantements.esp`
![image](https://user-images.githubusercontent.com/1944639/44171750-08253580-a0d3-11e8-83c1-b59901e898e0.png)

2018-08-15 20:41 UTC, MacSplody commented on masterlist.yaml
> +      - 'Dr_Bandolier.esp'
- 'Dr_Bandolier.esp' is not needed in `after` as it's a master.

2018-08-15 20:45 UTC, CptMcSplody commented on masterlist.yaml
> +        name: Bandolier - Bags and Pouches for NPC - Winter is Coming and Cloaks of Skyrim Patch
It's purely aesthetic but I usually keep `url` keys just under the `name` key for consistency.

2018-08-15 20:55 UTC, MacSplody requested changes
Okay so I need you to add `inc` entries for all standalone version so that only one version is used.

You can remove any Req & After entries where the plug-in is a master, as LOOT will handle requires and load after automatically for masters.

2018-08-15 21:18 UTC, CptMcSplody commented on masterlist.yaml
> +      - Invent
You don't need the `Invent` tag as that is for changes to `NPC_` or `CONT` Container records.

The following Bash tags can be added as well to all your plug-ins.
```yaml
    tag:
      - Names
      - Stats
```

2018-08-16 00:16 UTC, coco9515 commented
Ok, I think I did everything needed. Could you check ? Thank you for your time :)

2018-08-16 00:21 UTC, MacSplody approved these changes
Yeah looks good, Thanks for the contribution.

2018-08-16 00:29 UTC, merged