Updated Cleaning Data
loot/skyrimse pull request #2944
Opened 2024-06-17 11:58 UTC by RacerBG

Just some random cleaning data updates based on my crrent load order.

2024-06-17 12:03 UTC, sibir-ine commented
Thanks, can you please list version numbers (& versions where applicable) of each?

2024-06-17 12:05 UTC, RacerBG commented
> Thanks, can you please list version numbers (& versions where applicable) of each?

Could you please elaborate? I'm new to this process. :smiley:

2024-06-17 12:26 UTC, sibir-ine commented
For each of the plugins, list its version number when you downloaded it. For instance, if you downloaded v2.0 of example mod A & included its cleaning data in the PR, please state that its cleaning corresponds to v2.0 of the mod. Further, if there are multiple versions of the mod available, please specify the version(s) you've provided cleaning data for. For instance, if mod A has option 1 & option 2 available for download, each with the same plugin filename but different contents, & you've only provided cleaning data for option 1, please state this.

2024-06-17 20:53 UTC, RacerBG commented
SkyUI - 5.2SE
Unique Uniques SE Re-Ported - 2.3.3
Civil War Aftermath SE - 1.9
Guard Dialogue Overhaul SE (ESL version) - 3.0
Misc Dialogue Edits - 1.9.5.2
SkyTEST - Realistic Animals and Predators SE - 1.65.22
Even Better Quest Objectives SE - EBQO SE - 1.10.0
After the Civil War - Siege Damage Repairs - 2.6.0
The Choice is Yours - 2.7
YOT - Your Own Thoughts SE - First Person Messages - 1.21AE
Beyond Skyrim - Wares of Tamriel SE - 1.5.3
Civil War Aftermath SE - 1.9
JK's Skyrim - 1.7

2024-06-18 06:41 UTC, sibir-ine requested changes

2024-06-18 06:41 UTC, sibir-ine commented on masterlist.yaml
> +        util: 'SSEEdit v4.1.5f'
Double-checked this one, & it looks like you've cleaned this one previously. I get the checksum you got after I clean it:

```suggestion
    dirty:
      - <<: *quickClean
        crc: 0xD6093F62
        util: '[SSEEdit v4.1.5g](https://www.nexusmods.com/skyrimspecialedition/mods/164)'
        itm: 9
```

2024-06-18 06:41 UTC, sibir-ine commented on masterlist.yaml
> +        util: 'SSEEdit v4.1.5f'
Two of those checksums are from the other version, so they should be kept.

```suggestion
      # Redux, True GDO Port
      - crc: 0x6ABC1129
        util: 'SSEEdit v4.0.2f'
      # Redux
      - crc: 0x82FE6344
        util: 'SSEEdit v4.0.2f'
      # SE
      - crc: 0x21C5C3DB
        util: 'SSEEdit v4.1.5f'
```

2024-06-18 06:41 UTC, sibir-ine commented on masterlist.yaml
> +        util: 'SSEEdit v4.1.5f'
It looks like you provided cleaning data for the USSEP version, the other version should be kept.

```suggestion
      # USSEP
      - crc: 0xDF1DDA2D
        util: 'SSEEdit v4.1.5f'
      # Non-USSEP
      - crc: 0x1FC5AB07
        util: 'SSEEdit v4.0.4c'
```

2024-06-18 06:41 UTC, sibir-ine commented on masterlist.yaml
> +        util: 'SSEEdit v4.1.5f'
```suggestion
      # AE
      - crc: 0x2D1BF884
        util: 'SSEEdit v4.1.5f'
      # SE
      - crc: 0x63C713B2
        util: 'SSEEdit v4.0.3h (Hotfix 1)'
      # SE, Alt. Game Mechanics Vanilla
      - crc: 0x5518CDFF
        util: 'SSEEdit v4.0.3h (Hotfix 1)'
```

2024-06-18 06:41 UTC, sibir-ine commented on masterlist.yaml
> +        util: 'SSEEdit v4.1.5f'
```suggestion
        util: 'SSEEdit v4.1.5f'
      # No Dragon Attack
      - crc: 0x51F9FAE2
        util: 'SSEEdit v4.0.3'
```

2024-06-19 06:50 UTC, sibir-ine approved these changes
Thanks!

2024-06-19 06:52 UTC, merged